#!/usr/bin/python

from PySide6.QtGui import QGuiApplication
from PySide6.QtQml import QQmlApplicationEngine

# nvidia shenanigangs TODO: do i still need this?
from PySide6.QtCore import Qt
from PySide6.QtCore import QCoreApplication
QCoreApplication.setAttribute(Qt.AA_ShareOpenGLContexts, True)

app = QGuiApplication([])
eng = QQmlApplicationEngine("main.qml")

# die on ctrl+c in terminal
import signal
signal.signal(signal.SIGINT, signal.SIG_DFL)

app.exec_()
